spring:
  application:
    name: config-client
  cloud:
    config:
      profile: dev
      label: master
      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: config-server
server:
  port: 8811
enreka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/



